name: "gliner_bi_encoder"
backend: "onnxruntime"
max_batch_size: 0

input [
  {
    name: "labels_embeddings"
    data_type: TYPE_FP32
    dims: [ -1, 768 ]
  },
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [ -1, -1 ]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [ -1, -1 ]
  },
  {
    name: "words_mask"
    data_type: TYPE_INT64
    dims: [ -1, -1 ]
  },
  {
    name: "text_lengths"
    data_type: TYPE_INT64
    dims: [ -1, 1 ]
  },
  {
    name: "span_idx"
    data_type: TYPE_INT64
    dims: [ -1, -1, 2 ]
  },
  {
    name: "span_mask"
    data_type: TYPE_BOOL
    dims: [-1, -1 ]
  }
]

output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ -1, -1, 12, -1 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

optimization {
  graph: {
    level: 1
  }
} 