# SPDX-FileCopyrightText: Copyright (c) 2022-2024, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This recipe splits into packages - morpheus-core, morpheus-dfp and morpheus-llm
{% set version = environ.get('GIT_VERSION', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}

package:
  name: morpheus-split
  version: {{ version }}

source:
  git_url: ../../../..

outputs:
  ############################### morpheus-core #############################
  - name: morpheus-core
    type: conda_v2
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda_{{ cuda_compiler_version }}_py{{ python }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      script_env:
        # Note: Setting a default value here will overwrite the value from the
        # shell! Defaults should be set in the run_conda_build.sh script
        - CMAKE_CUDA_ARCHITECTURES
        - MORPHEUS_CACHE_DIR
        - MORPHEUS_PYTHON_BUILD_STUBS
        - PARALLEL_LEVEL
      run_exports:
        - {{ pin_subpackage("morpheus-core", max_pin="x.x") }}
    script: morpheus_core_build.sh

    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cuda") }}
        - {{ compiler("cxx") }}
        - ccache
        - cmake =3.27
        - cuda-cudart-dev {{ cuda_compiler_version }}.* # Needed by CMake to compile a test application
        - cuda-version {{ cuda_compiler_version }}.*
        - ninja =1.11
        - pkg-config =0.29
        - sysroot_linux-64 =2.28
      host:
        # CUDA dependencies
        - cuda-cudart-dev {{ cuda_compiler_version }}.*
        - cuda-libraries-dev {{ cuda_compiler_version }}.* # required by matx for libcublas-dev
        - cuda-nvml-dev {{ cuda_compiler_version }}.*
        - cuda-nvrtc-dev {{ cuda_compiler_version }}.*
        - cuda-nvtx-dev {{ cuda_compiler_version }}.*
        - cuda-version {{ cuda_compiler_version }}.*
        # Non-CUDA dependencies
        - cudf {{ rapids_version }}
        - cython 3.0.*
        - glog >=0.7.1,<0.8
        - libcudf {{ rapids_version }}
        - librdkafka >=1.9.2,<1.10.0a0
        - mrc {{ minor_version }}
        - nlohmann_json 3.11.*
        - pip
        - pybind11-stubgen 0.10.5
        - python {{ python }}
        - rapidjson 1.1.0
        - scikit-build 0.17.6
        - versioneer-518
        - zlib 1.3.1 # required to build triton client
      run:
        # Runtime only requirements. This + setup.py is the definitive runtime requirement list
        # This should be synced with `runtime` in dependencies.yaml
        - appdirs
        - beautifulsoup4
        - click >=8
        - cuda-version {{ cuda_compiler_version }}.*
        - cudf
        - cupy # Version determined from cudf
        - datacompy =0.10.*
        - dill =0.3.7
        - docker-py =5.0.*
        - elasticsearch ==8.9.0
        - feedparser =6.0.*
        - grpcio =1.62.*
        - mlflow>=2.10.0,<3
        - mrc
        - networkx=2.8.8
        - numpydoc =1.5.*
        - pydantic
        - pluggy =1.3.*
        - python
        - python-confluent-kafka >=1.9.2,<1.10.0a0
        - python-graphviz
        - rapids-dask-dependency {{ rapids_version }} # provides dask and distributed
        - requests
        - requests-cache =1.1.*
        - scikit-learn =1.3.2.*
        - sqlalchemy <2.0 # 2.0 is incompatible with pandas=1.3
        - tqdm =4.*
        - tritonclient =2.34.*
        - typing_utils =0.1.*
        - watchdog =3.0.*
        - websockets
    test:
      imports:
        - morpheus
      requires:
        - cuml {{ rapids_version }}.*
        - pynvml
        - pytest-asyncio
        - pytest-benchmark
        - pytest-cov
        - pytest =7.4.4
      source_files:
        - pyproject.toml
        - scripts/fetch_data.py
        - tests/*
      script: morpheus_core_test.sh

  ############################### morpheus-dfp #############################
  - name: morpheus-dfp
    type: conda_v2
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda_{{ cuda_compiler_version }}_py{{ python }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      script_env:
        - CMAKE_CUDA_ARCHITECTURES
        - MORPHEUS_CACHE_DIR
        - MORPHEUS_PYTHON_BUILD_STUBS
        - PARALLEL_LEVEL
      run_exports:
        - {{ pin_subpackage("morpheus-dfp", max_pin="x.x") }}
    script: morpheus_dfp_build.sh

    requirements:
      build:
        - ccache
        - cmake =3.27
      host:
        - {{ pin_subpackage('morpheus-core', exact=True) }}
        - pip
        - python {{ python }}
        - scikit-build 0.17.6
        - versioneer-518
      run:
        - {{ pin_subpackage('morpheus-core', exact=True) }}

    test:
      imports:
        - morpheus_dfp
      requires:
        - cuml {{ rapids_version }}.*
        - pynvml
        - pytest-asyncio
        - pytest-benchmark
        - pytest-cov
        - pytest =7.4.4
      source_files:
        - pyproject.toml
        - scripts/fetch_data.py
        - tests/*
      script: morpheus_dfp_test.sh

  ############################### morpheus-llm #############################
  - name: morpheus-llm
    type: conda_v2
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda_{{ cuda_compiler_version }}_py{{ python }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      script_env:
        - CMAKE_CUDA_ARCHITECTURES
        - MORPHEUS_CACHE_DIR
        - MORPHEUS_PYTHON_BUILD_STUBS
        - PARALLEL_LEVEL
      run_exports:
        - {{ pin_subpackage("morpheus-llm", max_pin="x.x") }}
    script: morpheus_llm_build.sh

    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - ccache
        - cmake =3.27
        - ninja =1.11
        - pkg-config =0.29
      host:
        # morpheus-core has to be at the top. changing that order will result in different
        # package versions getting installed creating unexpected version conflicts.
        - {{ pin_subpackage('morpheus-core', exact=True) }}
        - cython 3.0.*
        - glog >=0.7.1,<0.8
        - pip
        - pybind11-stubgen 0.10.5
        - python {{ python }}
        - rapidjson 1.1.0
        - scikit-build 0.17.6
        - versioneer-518
        - zlib 1.3.1 # required to build triton client
      run:
        - {{ pin_subpackage('morpheus-core', exact=True) }}

    test:
      imports:
        - morpheus_llm
      requires:
        - cuml {{ rapids_version }}.*
        - pynvml
        - pytest-asyncio
        - pytest-benchmark
        - pytest-cov
        - pytest =7.4.4
      source_files:
        - pyproject.toml
        - scripts/fetch_data.py
        - tests/*
      script: morpheus_llm_test.sh
 
about:
  home: https://github.com/nv-morpheus/Morpheus
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Morpheus Cybersecurity Library
