name: "root-cause-binary-onnx",
platform: "onnxruntime_onnx",
backend: "onnxruntime",
max_batch_size: 32,
input: [
    {
        name: "input_ids",
        data_type: TYPE_INT64,
        dims: [ 128 ]
    },
    {
        name: "attention_mask",
        data_type: TYPE_INT64,
        dims: [ 128 ]
    }
],
output:[
    {
        name: "output",
        data_type: TYPE_FP32,
        dims: [ 2 ]
    }
]

