# SPDX-FileCopyrightText: Copyright (c) 2022-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{% set version = environ.get('GIT_VERSION', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set py_version=environ.get('CONDA_PY', '3.10') %}
{% set cuda_version='.'.join(environ.get('CUDA', '11.8').split('.')[:2]) %}
{% set cuda_major=cuda_version.split('.')[0] %}
{% set rapids_version = "23.02" %}

package:
  name: morpheus-split
  version: {{ version }}

source:
  git_url: ../../../..

outputs:

  - name: morpheus
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda_{{ cuda_version }}_py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      script_env:
        # Note: Setting a default value here will overwrite the value from the
        # shell! Defaults should be set in the run_conda_build.sh script
        - CMAKE_CUDA_ARCHITECTURES
        - MORPHEUS_PYTHON_BUILD_STUBS
        - MORPHEUS_CACHE_DIR
        - PARALLEL_LEVEL
      run_exports:
        - {{ pin_subpackage("morpheus", max_pin="x.x") }}
      entry_points:
        - morpheus = morpheus.cli:run_cli
    script: morpheus_build.sh

    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("cuda") }}
        - ccache
        - cmake 3.24
        - cuda-cudart-dev # Needed by CMake to compile a test application
        - ninja
      host:
        - cuda-cudart
        - cudf {{ rapids_version }}
        - cython >=0.29,<0.30
        - libcudf {{ rapids_version }}
        - librdkafka 1.7
        - mrc {{ minor_version }}
        - pip
        - pyarrow * *_cuda # Ensure we get a CUDA build. Version determined by cuDF
        - pybind11-stubgen 0.10.5
        - python {{ python }}
        - rapidjson 1.1
        - scikit-build 0.17.1
        - versioneer-518

        # Remove cudatoolkit once `mamba repoquery whoneeds cudatoolkit` is empty. For now, we need to specify a version
        - cudatoolkit {{ cuda_version }}.*
      run:
        # Runtime only requirements. This + setup.py is the definitive runtime requirement list
        - {{ pin_compatible('cuda-cudart', min_pin='x.x', max_pin='x') }}
        - click >=8
        - configargparse 1.5.*
        - cudf
        - cudf_kafka {{ rapids_version }}.*
        - cupy # Version determined from cudf
        - datacompy 0.8.*
        - dill
        - distributed
        - docker-py 5.0.*
        - grpcio # Version determined from cudf
        - libmrc
        - mlflow >1.29,<2
        - mrc
        - networkx 3.1.*
        - numpydoc 1.4.*
        - pandas 1.3.*
        - pluggy 1.0.*
        - pyarrow * *_cuda # Ensure we get a CUDA build. Version determined by cuDF
        - python
        - scikit-learn 1.2.2
        - tqdm 4.*
        - typing_utils 0.1.*
        - watchdog 2.1.*
      run_constrained:
        # Since we dont explicitly require this but other packages might, constrain the versions.
        - {{ pin_compatible('cudatoolkit', min_pin='x.x', max_pin='x') }}
    test:
      requires:
        - gputil
        - pytest
        - pytest-cov
        - pytest-benchmark
        # test that cuml can be installed in the env
        - cuml {{ rapids_version }}
      source_files:
        - docker/conda/environments/*
        - pyproject.toml
        - scripts/fetch_data.py
        - tests/*
      imports:
        - morpheus
      commands:
          - echo # make sure test requirements get installed

about:
  home: https://github.com/nv-morpheus/Morpheus
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Morpheus Cybersecurity Library
