pipeline {
    agent any
    options {
        disableConcurrentBuilds(abortPrevious: true)
    }
    stages {
        stage('Build') {
            options {
                timeout(time: 6, unit: 'HOURS')
            }
            environment {
                PARALLEL_LEVEL = '16'
                PYTHON_VER = '3.8'
                RAPIDS_VER = '21.10'
                CUDA_VER = '11.4'
                HOME = "${WORKSPACE}"
            }
            agent {
                docker {
                  image 'gpuci/miniforge-cuda:11.4-devel-ubuntu20.04'
                  label 'driver-495'
                  args '--runtime "nvidia" -e "NVIDIA_VISIBLE_DEVICES=$EXECUTOR_NUMBER"'
                }
            }
            steps {
                sh "./ci/scripts/jenkins_build.sh"
            }
        }
    }
    post {
        always {
                cleanWs(
                    deleteDirs: true,
                    externalDelete: 'sudo rm -rf %s'
                )
        }
    }
}
