pipeline {
    agent any
    options {
        disableConcurrentBuilds(abortPrevious: true)
    }
    stages {
        stage('Build') {
            options {
                timeout(time: 6, unit: 'HOURS')
            }
            environment {
                PARALLEL_LEVEL = '10'
                PYTHON_VER = '3.8'
                RAPIDS_VER = '21.10'
                CUDA_VER = '11.4'
                HOME = "${WORKSPACE}"
            }
            agent {
                docker
                .image('gpuci/miniforge-cuda:11.4-devel-ubuntu20.04')
                .inside("""
                  --runtime=nvidia
                  -e NVIDIA_VISIBLE_DEVICES=$EXECUTOR_NUMBER
                """)
                {
                  label 'driver-495'
                }
            }
            steps {
                sh "./ci/scripts/jenkins_build.sh"
            }
        }
    }
}
